name: CI/CD to GKE (Artifact Registry)

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: storied-radius-473212-g7
  LOCATION: us-central1        # Artifact Registry location
  REPOSITORY: iris-api-cicd
  IMAGE_NAME: iris-api
  CLUSTER_NAME: gke-iris-cluster-ga6

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure docker for Artifact Registry
      run: gcloud auth configure-docker ${{ env.LOCATION }}-docker.pkg.dev --quiet

    - name: Build and push Docker image to artifact registry
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
          ${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          ${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
        file: ./Dockerfile

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: gke-iris-cluster-ga6
        location: us-central1
        project_id: ${{ env.PROJECT_ID }}

    - name: Set image in k8s deployment
      run: |
        kubectl set image deployment/iris-api iris-container=${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} --record
        kubectl rollout status deployment/iris-api --timeout=120s
